---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demoBinding
subjects:
  - kind: ServiceAccount
    name: observability-collector
    namespace: opentelemetry
roleRef:
  kind: ClusterRole
  name: collector-cluster-role
  apiGroup: rbac.authorization.k8s.io
