apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observability
  namespace: opentelemetry
spec:
  # Make sure the operator uses a contrib distribution instead of a stock otel collector image
  image: otel/opentelemetry-collector-contrib:0.79.0
  config: |
    # See https://github.com/open-telemetry/opentelemetry-collector-contrib for additional definitions.
    receivers:
      loki:
        protocols:
          http:
        use_incoming_timestamp: true

    processors:

      attributes:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: container
          - action: insert
            key: loki.format
            value: raw

      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:
        verbosity: normal
      loki:
        endpoint: http://loki-loki-distributed-gateway.grafana-loki.svc.cluster.local/loki/api/v1/push

    service:
      pipelines:
        logs:
          receivers: [loki]
          processors: [attributes]
          exporters: [loki]
