apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
  labels:
    app: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy-container
          image: ubuntu:20.04
          command: ["/bin/bash", "-c"]
          args:
            - |
              counter=1;
              while true; do
                echo "Dummy Message Counter: $counter";
                counter=$((counter+1));
                sleep 1;
              done
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          ports:
            - containerPort: 8080
